language: java
jdk:
- openjdk11

branches:
  only:
  - main

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"

script: "./gradlew clean build"

notifications:
  email:
    recipients:
    - asc0323@gmail.com

before_install:
- openssl aes-256-cbc -K $encrypted_1116e8e6e492_key -iv $encrypted_1116e8e6e492_iv
  -in application.yml.enc -out application.yml -d

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: webnote-deploy # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    wait-until-deployed: true
    on:
      repo: SeongcheolAhn/webnote #Github 주소
      branch: main
