version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/travis/build/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall: # 배포가 끝나면 아래 명령어를 실행
    - location: deploy.sh
      timeout: 60
      runas: ec2-user